### PR TITLE
0.2.0

### PR DESCRIPTION
**Pull request by aldanor**

### CODE REVIEW

**Comment by aldanor** [comment]
@kkirstein Hi! I was wondering if you're still interested and whether you could take a look -- I fixed all problems with MSVC builds, hacked around missing dllimport on Windows, all tests pass just fine on my machine with the official 1.8.16 HDF5 binary (Visual Studio 2015), and Rust 1.8.0-msvc!

However, the AppVeyor builds seem to hang on the build script for `hdf5_rs` for some reason using the same config and I can't reproduce the problem, I wonder if you could try to clone / run tests on your box?

**Comment by aldanor** [comment]
https://ci.appveyor.com/project/aldanor/hdf5-rs/build/0.1.104/job/b4e33j8jevw5i29t

Stuck on running the build script for `libhdf5-sys`...

**Comment by aldanor** [comment]
@kkirstein ok, I have solved it so no worries 👍

**Comment by kkirstein** [comment]
@aldanor Currently, I don't have a working rust/hdf5 setup on my windows box, so I am glad you could solve the issue.

**Pull request merged**
