### PR TITLE
basic appveyor ci

### PR DESCRIPTION
**Pull request by kkirstein**
This contains a basic appveyor integration:
- configuration is completely done with appveyor.yml (no GUI setup)
- a binary verson of hdf5.dll is downloaded from GitHub
- builds for rust 1.1 & nightly are checked

Todos:
- add build of hdf5 lib (needs cmake & MinGW)
- add 32bit build (?)
- add *-msvc target of rust

You have to setup a project on appveyor for your repo and change the link of the build status badge in Readme for this to work in your repo.

### CODE REVIEW

**Comment by andreabedini** [comment]
my 2c on the README: it makes total sense of HDF people to use MSVC on Windows rather than mingw. Actually Rust is supposed to work with MSVC too and they are going to get there soon see e.g. rust-lang/rfcs#1061.

**Comment by aldanor** [comment]
@kkirstein This is great, thanks a lot! I will try to set up the appveyor repo tonight and then merge this in.

Could you please squash this PR?

**Comment by aldanor** [comment]
@andreabedini we have already discussed this in #4 :) It would be best to support both mingw and msvc once it's out of course.

**Comment by andreabedini** [comment]
@aldanor sorry, I have been out of the loop :)

**Comment by kkirstein** [comment]
@aldanor I will try to squash this PR, so you don't see all my flaws (I'm not an Git-expert and already merged my branch, but it should be possible anyway..).
@andreabedini mcvs target is already on my todo list, but with low prio. I should give it fast try.

**Comment by kkirstein** [comment]
@aldanor There is another PR with a squashed commit from my appveyor branch.

**Comment by aldanor** [comment]
Closed in favor of #7.

**Comment by aldanor** [comment]
@kkirstein You could have just `git push --force` so you wouldn't have to create a new PR, I think :)

**Pull request closed without merging**
